version: "3.8"

services:
  basic_auth:
    image: mysql:latest
    container_name: mysql_basic
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_DATABASE: "basic"
      MYSQL_USER: "default"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - /home/albertoradtke/Documents/project/basic_auth/mysql/data:/var/lib/mysql
